package com.sedsoftware.bagcue.compose.theme

import androidx.compose.ui.graphics.Color

// Static BagCue navy/apricot brand palette.
// Navy actions, warm secondary accents, neutral surfaces; paired roles checked for contrast.

internal val Seed = Color(0xFF263653)

internal val PrimaryLight = Color(0xFF354D70)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFDDE7F5)
internal val OnPrimaryContainerLight = Color(0xFF263653)
internal val SecondaryLight = Color(0xFF80502D)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFF7D9BC)
internal val OnSecondaryContainerLight = Color(0xFF3C2717)
internal val TertiaryLight = Color(0xFF54647C)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFDCE5F4)
internal val OnTertiaryContainerLight = Color(0xFF29384E)
internal val ErrorLight = Color(0xFFBB152C)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD8)
internal val OnErrorContainerLight = Color(0xFF410007)
internal val BackgroundLight = Color(0xFFFFFBF7)
internal val OnBackgroundLight = Color(0xFF20242C)
internal val SurfaceLight = Color(0xFFFFFBF7)
internal val OnSurfaceLight = Color(0xFF20242C)
internal val SurfaceVariantLight = Color(0xFFE3E4EA)
internal val OnSurfaceVariantLight = Color(0xFF454A55)
internal val OutlineLight = Color(0xFF757A85)
internal val OutlineVariantLight = Color(0xFFC5C8D0)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF30343C)
internal val InverseOnSurfaceLight = Color(0xFFF2F0ED)
internal val InversePrimaryLight = Color(0xFFB4C9EB)
internal val SurfaceDimLight = Color(0xFFDEDAD6)
internal val SurfaceBrightLight = Color(0xFFFFFBF7)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF8F4F0)
internal val SurfaceContainerLight = Color(0xFFF2EEEA)
internal val SurfaceContainerHighLight = Color(0xFFECE8E4)
internal val SurfaceContainerHighestLight = Color(0xFFE6E2DE)

internal val PrimaryDark = Color(0xFFB4C9EB)
internal val OnPrimaryDark = Color(0xFF1D304D)
internal val PrimaryContainerDark = Color(0xFF344B6B)
internal val OnPrimaryContainerDark = Color(0xFFDDE7F5)
internal val SecondaryDark = Color(0xFFF0BE91)
internal val OnSecondaryDark = Color(0xFF492B13)
internal val SecondaryContainerDark = Color(0xFF634125)
internal val OnSecondaryContainerDark = Color(0xFFFFDCBF)
internal val TertiaryDark = Color(0xFFBDCAE0)
internal val OnTertiaryDark = Color(0xFF28364B)
internal val TertiaryContainerDark = Color(0xFF3E4D62)
internal val OnTertiaryContainerDark = Color(0xFFDCE5F4)
internal val ErrorDark = Color(0xFFFFB3B1)
internal val OnErrorDark = Color(0xFF680011)
internal val ErrorContainerDark = Color(0xFF92001C)
internal val OnErrorContainerDark = Color(0xFFFFDAD8)
internal val BackgroundDark = Color(0xFF13171F)
internal val OnBackgroundDark = Color(0xFFE4E5EA)
internal val SurfaceDark = Color(0xFF13171F)
internal val OnSurfaceDark = Color(0xFFE4E5EA)
internal val SurfaceVariantDark = Color(0xFF454A55)
internal val OnSurfaceVariantDark = Color(0xFFC5C8D0)
internal val OutlineDark = Color(0xFF8F949F)
internal val OutlineVariantDark = Color(0xFF454A55)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFE4E5EA)
internal val InverseOnSurfaceDark = Color(0xFF30343C)
internal val InversePrimaryDark = Color(0xFF354D70)
internal val SurfaceDimDark = Color(0xFF13171F)
internal val SurfaceBrightDark = Color(0xFF383D47)
internal val SurfaceContainerLowestDark = Color(0xFF0E1219)
internal val SurfaceContainerLowDark = Color(0xFF1B1F28)
internal val SurfaceContainerDark = Color(0xFF1F242D)
internal val SurfaceContainerHighDark = Color(0xFF292E37)
internal val SurfaceContainerHighestDark = Color(0xFF343942)
